### ISSUE TITLE
Editor can add a title to the document

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#131]
## Front end @jiayingy 
- [ ] webapp need to allow editor to set the title field
- [ ] webapp need to allow editor to update the title field

## Back end @tayjiehao 
- [ ] webapp/fileManager need to accept the title field
- [ ] webapp/fileManager need to store the title field
- [ ] webapp/fileManager need to retrieve the title field

**Comment by amoshydra** [comment]
This requirement may concern [Files Manager](https://github.com/nus-mtp/lecture-note-2.0/issues?q=is%3Aopen+is%3Aissue+label%3Aus%3A4.FilesManagement)

**Comment by tayjiehao** [comment]
File name will be used as the title of the document.
