### ISSUE TITLE
Editor can manage page break within the Pages document

### ISSUE THREAD

**Issue by chuajiaxuan** [nus-mtp/lecture-note-2.0#14]

**Comment by amoshydra** [comment]
See [codes](https://github.com/nus-mtp/lecture-note-2.0/commit/c27d44c684864ed9fd5b02d62c118a8c61b8938b#diff-38b7608a5dc902c3e18f3d622f6747e3R36)

Page break for both Slides and Pages can be added by typing

`<pagebreak>`

into the markdown document.
