### ISSUE TITLE
Research on automated Browser testing on travis

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#156]

**Comment by tharain** [comment]
[Suggestion] Research into 'vows.js' to run asynchronous behavior driven code

**Comment by amoshydra** [comment]
@tharain We can look into using night [nightwatchjs](http://nightwatchjs.org) for our automated browser testing. Since it is included in our repo already.

[Example](https://github.com/nus-mtp/lecture-note-2.0/blob/development/sashimi-webapp/test/e2e/specs/test.js) we are currently using.
```javascript
// For authoring Nightwatch tests, see
// http://nightwatchjs.org/guide#usage

module.exports = {
  'default e2e tests': function test(browser) {
    // automatically uses dev Server port from /config.index.js
    // default: http://localhost:8080
    // see nightwatch.conf.js
    const devServer = browser.globals.devServerURL;

    browser
      .url(devServer)
      .waitForElementVisible('#app', 5000)
      .assert.elementPresent('.hello')
      .assert.containsText('h1', 'Welcome to Your Vue.js App')
      .assert.elementCount('img', 1)
      .end();
  },
};
```

However, I suspect we currently can only get these automated testing done locally (not in Travis. although external paid service are available e.g. SauceLabs).

**Comment by amoshydra** [comment]
Closed: Will not solve. Browser testing it to be done in local machine only.

Our project currently come with nightwatchjs, selenium and chrome webdriver.
Additional browser (e.g. Safari and IE) can be added in the future.
