### ISSUE TITLE
Implementation the FileManager API

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#176]
API Suggestion:
- get root folder
- get list of file
...

**Comment by tayjiehao** [comment]
# To Do

## `Operations` Component

**`core`**
- [x] `loadDB()`
- [x] `init()`
- [x] `getFile()`
- [x] `getFolder()`

**`History`**
- [x] `update()`
- [x] `previous()`
- [x] `history()`

**`Search`**
- [x] `fileOnly()`
- [x] `folderOnly()`
- [x] `all()`

## `Data` Component
**`File`**
- [x] `delete()`
- [x] `save()`
- [x] `load()`
- [x] `move()`
- [x] `remove()`

**`Folder`**
- [x] `createFolder()`
- [x] `createFile()`
- [x] `remove()`
- [x] `renameFolder()`

**`idMap`**
- [x] `addFileToMap()`
- [x] `addFolderToMap()`
- [x] `getFileFromMap()`
- [x] `getFolderFromMap()`
- [x] `removeFileFromMap()`
- [x] `removeFolderFromMap()`
