### ISSUE TITLE
Rename `wrapper` component to better signify the functionality of the component

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#179]

**Comment by amoshydra** [comment]
@chuajiaxuan assign this to you, since you will be in charge of this component for now.

**Comment by chuajiaxuan** [comment]
Has been renamed as documentPackager! https://github.com/nus-mtp/lecture-note-2.0/commit/d75304ae9477af1a1ca0dfb23d6a41ecdfd62864
