### ISSUE TITLE
Webapp will sanitise potential XSS execution for markdown-it

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#181]
Replace all `<script>` with `&lt;script&gt;`
You may also use external library to do the sanitisation

**Comment by chuajiaxuan** [comment]
Will try using this [HTML XSS Filter library](https://github.com/leizongmin/js-xss)!

**Comment by chuajiaxuan** [comment]
HTML XSS Filter library has been implemented, currently working! See this [PR](https://github.com/nus-mtp/lecture-note-2.0/pull/187) and this commit [c666a97](https://github.com/nus-mtp/lecture-note-2.0/commit/c666a9722bd2f768caab1d0b0a14b07217521131).
