### ISSUE TITLE
Suspect that Vue router not properly configured

### ISSUE THREAD

**Issue by chuajiaxuan** [nus-mtp/lecture-note-2.0#189]
There is a problem when testing the Table of Content plugin in webapp. Currently unit test show that plugin is working with the attributes generation for the header tags. However, in webapp, links to each header is not working properly. It is suspected that the Vue router is not properly configured for this. Link for webapp editor is "http://.../#/content", clicking on the TOC links will cause "/#/content" to be replaced by the respective attributes (e.g. clicking on Header1 link will result in "/#/content" becoming "/#/header1")

**Comment by amoshydra** [comment]
Fixed #201
