### ISSUE TITLE
Highlightjs: The contrast between the background and foreground color is low

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#191]
Consider choosing a theme that provide higher contrast.

**Markdown**

```markdown
# Hello

```javascript
function hello(data) {
	console.log(data);
}
```

**Result**  

<img src="https://i.imgur.com/Ftj2CIJ.png" height="160">

<img height="30">

**Comment by chuajiaxuan** [comment]
**Update**  - highlighting changed!

<img src="http://i.imgur.com/RoFGHqZ.png" height="160">

<img height="30">

**Comment by amoshydra** [comment]
Looks great
