### ISSUE TITLE
<pagebreak> not working as intended

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#221]
`<pagebreak>` need to be written as

```
<pagebreak>
</pagebreak>
```

otherwise, it will not work, or cause the subsequent pagebreak tag to stop working.

Expected behaviour, <pagebreak> should be treated as a self closing tag.

**Comment by amoshydra** [comment]
Unfortunately it seems like HTML parser can only parse specific self closing tag. Custom element cannot be a made with a self-closing tag.

**Resolution:**
I will have to resolve to using
`<br page>` for manual page break creation now.

@chuajiaxuan, I will need your help to whitelist the `page` attribute on `br` tag. #237
```javascript
whiteList.br.push('page');
```

**Reference:**
- http://stackoverflow.com/questions/23961178/do-custom-elements-require-a-close-tag
- https://www.w3.org/TR/html/syntax.html#void-elements

**Comment by amoshydra** [comment]
Done with 4728712b

manual page break will now use:
```html
<br page>
```

It should sound like "**br***eak* **page**"

**Comment by chuajiaxuan** [comment]
Added in the `page` attribute to `br` tag already!
