### ISSUE TITLE
Look into potential SQL injection

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#245]
See @tayjiehao's comment https://github.com/nus-mtp/lecture-note-2.0/pull/241#pullrequestreview-25983199

**Comment by tharain** [comment]
@amoshydra err....I have thought about it before and therefore I restrict my queries to not able to parse in full strings. But the problem is indexeddb is not exactly secure because the data is apparently unencrpyted. And everyone can input a direct indexeddb query I guess. >.< If we move on to encryption, then I guess the whole database structure has to change as I cannot query a encrypted data especially for searching. 

> One of these security risks lies with the HTML5 client-side database. It appears that data stored on the client file system is unencrypted. https://www.researchgate.net/publication/281066023_Some_Potential_Issues_with_the_Security_of_HTML5_IndexedDB

**Comment by amoshydra** [comment]
I see. Yeah I guess someone can even open up the developer console and start messing up with the indexedDB directly.

Fortunately all the data that will be stored in indexedDB is only going to be user's data only (i assume).
Perhaps, additional care will be needed during the sync between the client local database with the server database.

@tharain @tayjiehao, what is your view on this matter? Let's assume that the user now have full access to entire client database (which they do, without even the need of SQL injection), do you see any potential danger or problem?

**Comment by amoshydra** [comment]
Perhaps, we will look into this again when we are doing the platform

**Comment by tharain** [comment]
hahaha my security knowledge is quite fundamental, but from my limited knowledge from CS2107:

**Possible dangers:**

1. sending data over insecure network and people can eavesdrop.
2. people trying to steal passwords due to malware or leakage or using encrypting software to brute force.
3. like you mentioned >.< SQL injection
4. DDOS (over-request until our server goes down, but I think this one not important for now .__.)

**Possible Solutions**
1.  password need to be hashed (with salt - optional - meaning a random number tied to the password before hashing to prevent same password to appear twice)
2.  close the access to SQL to only support 1 server request (dk how to do it need to google)
3.  Encryption and decryption wise...I have no idea of the implementation without a secure channel to send the private key.

**Comment by amoshydra** [comment]
### Regarding to the possible dangers:
1. All communication between the client and the server will be sent through HTTPS (HTTP over SSL). So the network is secure.
2. As I have mentioned in the previous post, I am making the assumption that the database in the client side will only be used to store information or data about the user only. So there will be two scenario that I can imagine for now:
    1. `Scenario 1` User have full control over the indexedDB.
    2. `Scenario 2` External malware manage to have control over the indexedDB.

    `Scenario 1` is the scenario that I was concerning in the previous post: 
    > Let's assume that the user now have full access to entire client database...
    
    `Scenario 2`. Yeah this could happen, provided if XSS is allowed to happen.
    For this to happen, the attacker will need to be able to execute JavaScript in the document in order to gain access to the indexedDB instance.
    This will depends on the HTML sanitizing of the markdown process (developed by us) and security of the browser (external factor).

3. This will be related to `Scenario 1`. Assuming that the user can openly change any value within the IndexedDB, what is the possible danger or problem?

4. Is this related to indexedDB? Or did you mean DDOS to our server in general?
---

### Discussion

What I see now is that, 1 malicious thing that the user could perform:
1. The user could possibly change his own organisation ID in order to get access to data without permission.

#### Below is a possible malicious behaviour and its countermeasure:
##### Two files:
1. File A - accessible only by ID 12345
2. File B - accessible only by ID 99999

##### Scenario:
1. Normal operation
    1. Client has **ID = 12345** and **Secret = 54321**
    2. Client requests for file A
    3. Server authenticates requester with ID and Secret
    4. Server checks if requester has permission to access file A
    5. Server accepts request and send file A to requester.
2. Unauthorized access
    1. Client requests for file B
    7. Server authenticates requester with ID and Secret
    8. Server checks if requester has permission to access file A
    9. Server rejects request since the ID has no permission
3. Attacking indexedDB
    1. Client changes its ID (by modifying indexedDB directly) to 99999
    *However he doesn't know the Secret of 99999*
    9. Client requests for file B
    10. Server failed to authenticate requester (since ID and secret doesn't match)
    11. Server rejects the request

Therefore, in this scenario, changes in the indexedDB does not allow user to gain unauthorized access to other data.

**Comment by tharain** [comment]
I personally feel that if its a case like that then the purpose of login is like for show >.<. I personally feel that the user will be given a session key upon login in which acts as a secret key to access those datas.

==================================================================

Previously:
I forgot to add that the attacker might brute force to login system so its better to add a delay of 1 s to login at the user interface.

==================================================================

But I think you made a good point at point 2 in possible dangers, but I think other than the user, the user still have to be able to access to its own files and folders. However the check should be done at the server side database, to ensure the user did not modify any critical data when updating. 

1. Critical data implies if the user has no write property, it will not be uploaded (Edit).
2. If the user edit the owner in its indexedDB, we can check from server side that it is invalid and correct the user side.
3. If the user modifies the datastructure in its indexedDB, this will be a huge problem and we treat as data corruption?? ie. From 'username: apple' to 'hackedname: apple'
4. If the user delete the no write file, should we prompt the user to re-download it?? In case it was accidentally deleted
5. If the file the user has read property no longer exists in the database (deleted by someone else), should we delete the file from the user database too?
6. We can retrieve all the files and folders the user have access to at the start to disallow illegal access or trying to read beyond whats there.

**Comment by tharain** [comment]
I guess fundamentally is fine now, but its not exactly an issue as they are just going to harm their own browser. Plus thankfully the alasql library is not yet fully implemented so there are nothing much they can take advantage of.
