### ISSUE TITLE
Sashimi Note brand name and title not layout correctly on Windows

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#286]
Sashimi Note logo title uses `"Avenir", Helvetica, Arial, sans-serif`.
Both Avenir and Helvetica is not a default font in Windows. Thus Arial is used to display the brand title instead.

<br>

<kbd>
<img src="http://i.imgur.com/GgWSoLy.png">
</kbd>

**Comment by jiayingy** [comment]
Fixed at 7f13fd2
