### ISSUE TITLE
Handle special character when renaming file/folder

### ISSUE THREAD

**Issue by tayjiehao** [nus-mtp/lecture-note-2.0#301]

**Comment by tayjiehao** [comment]
Should not contain the following special characters for file/folder name: !$%^&*()_+|~-=`{}[]:";'<>?,./

**Comment by amoshydra** [comment]
Escaping all of these symbol could be a bit too harsh on the user. Some possible useful filename/ title could be:
1. `Assignment (Edited)`
1. `DESKTOP_BACKUP`
1. `sashimi-note`
1. `[2] Media`
1. `2. Proposal`
1. `Gene & Society`

Perhaps we can at least retain `()_-[].& `

## Reference
This seems to be a good reference for some of the security concerned regarding filename
https://www.dwheeler.com/essays/fixing-unix-linux-filenames.html

1. Control characters in filenames are a terrible idea `\n\0`
2. Leading dashes in filenames are a terrible idea `-hello`
3. Spaces in filenames
4. Metacharacters in filenames are unfortunate `*?:[]"<>|(){}&'!\;$`

## Interesting behaviour
I have attempted to download a file containing illegal character on Chrome on Windows.
Upon downloading, it will replace all illegal character to -.
e.g. 
`<helloworld>` -> `-helloworld-`

Other browsers not tested yet as either their rename or download function failed to work for v0.1.3.

**Comment by tayjiehao** [comment]
Moved to Issue: #293
