### ISSUE TITLE
Entering " into filename will cause renaming to fail

### ISSUE THREAD

**Issue by amoshydra** [nus-mtp/lecture-note-2.0#304]
Consider adding input sanitation to all externally generated data (user input / other developer) before using it with the database.

Although #301 will handle part of this problem, it will be good for the database to do the sanitation itself too.

Potential target for file manager related API
1. User input
    1. Content data (handled)
    2. Filename
    3. Folder name
2. Other developers
    1. File path

**Comment by amoshydra** [comment]
The `"` replace strategy will fail when user try to type `\\\\\"`

#### Possible solution
Reference:
1. http://stackoverflow.com/questions/7744912/making-a-javascript-string-sql-friendly
2. http://php.net/manual/en/function.mysql-real-escape-string.php
3. https://www.owasp.org/index.php/SQL_Injection_Prevention_Cheat_Sheet#MySQL_Escaping

Code copied from stackoverflow, Paul d'Aoust
```javascript
function mysql_real_escape_string (str) {
    return str.replace(/[\0\x08\x09\x1a\n\r"'\\\%]/g, function (char) {
        switch (char) {
            case "\0":
                return "\\0";
            case "\x08":
                return "\\b";
            case "\x09":
                return "\\t";
            case "\x1a":
                return "\\z";
            case "\n":
                return "\\n";
            case "\r":
                return "\\r";
            case "\"":
            case "'":
            case "\\":
            case "%":
                return "\\"+char; // prepends a backslash to backslash, percent,
                                  // and double/single quotes
        }
    });
}
```
 
Do see the Cheat Sheet from owasp linked above, which could be useful for your search function.

```
 NUL (0x00) --> \0  [This is a zero, not the letter O]
 BS  (0x08) --> \b
 TAB (0x09) --> \t
 LF  (0x0a) --> \n
 CR  (0x0d) --> \r
 SUB (0x1a) --> \Z
 "   (0x22) --> \"
 %   (0x25) --> \%
 '   (0x27) --> \'
 \   (0x5c) --> \\
 _   (0x5f) --> \_ 
 all other non-alphanumeric characters with ASCII values less than 256  --> \c
 where 'c' is the original non-alphanumeric character.
```

**Comment by tharain** [comment]
done
