### ISSUE TITLE
User can delete an existing document

### ISSUE THREAD

**Issue by tharain** [nus-mtp/lecture-note-2.0#40]
- [ ] File Manager View to provide ui to delete an existing document (@jiayingy)
- [x] `webapp/filemanager` to provide api to delete an existing document (@tayjiehao)

**Comment by jiayingy** [comment]
For file: 32298a896ad63b02a2fba94e58702055c7273779
For folder: b02663a8f7691ae889fabf5e78463d697017b7f8
