### ISSUE TITLE
Editor can generate multiple document versions from the same single source

### ISSUE THREAD

**Issue by chuajiaxuan** [nus-mtp/lecture-note-2.0#53]
- [x] #155 Editor can generate a Slides format using a markdown source
- [x] #154 Editor can generate a Pages format using a markdown source

**Comment by chuajiaxuan** [comment]
- [ ] Editor can generate different presentation format using source
- [ ] Editor can generate different notes formate using the source

**Comment by amoshydra** [comment]
Done #199
