### ISSUE TITLE
Editor can undo a mistake

### ISSUE THREAD

**Issue by tharain** [nus-mtp/lecture-note-2.0#68]
- [ ] Editor can undo a keyboard character insertion
- [ ] Editor can undo a formatting command

**Comment by amoshydra** [comment]
Implementation details:
1. Each input should be packaged as a command that have its relevant `undo` function.
2. These command should be queued.
3. If user issue a `undo` command, the Webapp should execute the relevant `undo` function according to the sequence of the queue.

**Comment by amoshydra** [comment]
Packaging of command may not be necessary anymore.
Undo and redo is full functional with browser default behaviour.
