### ISSUE TITLE
Editor can create a different version of the document with part of the content selectively hidden

### ISSUE THREAD

**Issue by tayjiehao** [nus-mtp/lecture-note-2.0#96]

**Comment by chuajiaxuan** [comment]
Conditional Rendering is now working! But further implementation is needed on the UI/frontend side to use it for different document/version conditional rendering (e.g. hide content for tutorial version but show for answer key version.). See this [pull request](https://github.com/nus-mtp/lecture-note-2.0/pull/196) and this issue [349c84e](https://github.com/nus-mtp/lecture-note-2.0/commit/349c84e5534c5147ff2a94217953d37488260dc8).
